---
title: Welcome & landscape
author: David L Miller, Jason Roberts, Eric Rexstad

---



# Welcome


## Who are we?

  * David L Miller
    * Research fellow, CREEM, University of St Andrews
    * Worked on R distance sampling software since 2005
    * Author/maintainer of `Distance`, `mrds`, `dsm`, `readst`, `mmds`
  * Jason Roberts
    * Research fellow (?), MGEL, Duke University
    * [more bio info !]
    * Author of MGET toolbox for ArcGIS
  * Eric Rexstad (here virtually)
    * Senior research fellow, CREEM, University of St Andrews
    * Author of numerous papers on animal abundance estimation
    * Instructor at CREEM distance sampling workshops since 2005
    * Author "Distance Sampling: Methods and Applications" (w. Steve Buckland, Tiago Marques, Cornelia Odekoven)


## What is this course about?

  * Building practical spatial models using R and ArcGIS
  * Getting data out of ArcGIS and into R
  * Distance sampling detection functions
  * Spatial modelling with GAMs
  * Model checking
  * Predictions and visualisation



## What is this course not about?

  * Survey design
  * "Advanced" techniques
  * Basic statistics
  * Basic R
  * Basic ArcGIS


## Schedule & landscape

  1. Modelling detectability
  2. Spatial data in ArcGIS
  3. Spatial models in R (and how to check them)
  4. Getting and using appropriate covariates
  5. Making and visualising predictions

## Daily schedule

  * Can be found at [URL]
  * In rooms BLAH and BLAH
  * Starting at 9am, finish at 5:30pm.
  * Lunch 12:30pm to 2pm (nearest lunch venue is BLAH)


## Other info

  * Additional notes and bibliography available on course website [URL]
  * Slides/practicals/code also there
  * MozPad session at [URL], Eric can answer questions there
  * Extra code and links to be posted at MozPad, which will be archived for later

## Software

  * Using Arc and RStudio
  * If you have your own copies make correct software is installed:
    * instructions at [URL]
  * Computer classroom is already setup.

## Data

  * Sperm whale data from NOAA
  * East coast surveys
  * ...
  * Data can be downloaded at [URL]

## Let's get started...


