---
title: Detection function analysis of sperm whale data
author: David L Miller

---

# Preamble

```{r load-libraries}
library(rgdal)
library(ggplot2)
library(Distance)
library(knitr)
```

# Load the data

```{r load-data}
distdata <- readOGR("Analysis.gdb","Sightings")
distdata <- distdata@data
head(distdata)
```

Rename the columns to be compatible with `Distance`:
```{r rename-cols}
distdata$distance <- distdata$Distance
distdata$object <- distdata$SightingID
distdata$Sample.Label <- distdata$SegmentID
distdata$size <- distdata$GroupSize
```

# Exploratory analysis

```{r eda-covars}
par(mfrow=c(1,2))
# plot of size versus distance, linear model and LOESS smoother overlay
plot(distdata[c("size","distance")], xlab="Group size", ylab="Distance (m)",pch=19,col=rgb(0,0,0,0.4), cex=0.6)
# increase span from default 0.75 for slightly smoother curve
lo <- loess(distance ~ size, distdata, span=0.8)
lmm <- lm(distance ~ size, distdata)
preddat <- data.frame(size=seq(0,8,1))
lines(x=preddat$size, y=predict(lmm, preddat),lty=2)
lines(x=preddat$size, y=predict(lo, preddat))

plot(distdata[c("SeaState","distance")], xlab="Beaufort sea state", ylab="Distance (m)",pch=19,col=rgb(0,0,0,0.4), cex=0.6)
# increase span from default 0.75 for slightly smoother curve
lo <- loess(distance ~ SeaState, distdata, span=0.8)
lmm <- lm(distance ~ SeaState, distdata)
preddat <- data.frame(SeaState=seq(0,8,1))
lines(x=preddat$SeaState, y=predict(lmm, preddat),lty=2)
lines(x=preddat$SeaState, y=predict(lo, preddat))
```


```{r eda-dist}
hist(distdata$distance, xlab="Distance (m)")
```

```{r eda-dist-facet-seastate}
distdata$SeaStateCut <- cut(distdata$SeaState,seq(0,5,by=1), include.lowest=TRUE)
p <- ggplot(distdata)
p <- p + geom_histogram(aes(distance))
p <- p + facet_wrap(~SeaStateCut)
print(p)
```

```{r eda-dist-facet-survey}
p <- ggplot(distdata)
p <- p + geom_histogram(aes(distance))
p <- p + facet_wrap(~Survey)
print(p)
```




# Fit some detection functions


```{r support-make-table}
make_table <- function(models){

  extract_model_data <- function(model){
    c(summary(model)$ds$key,
      model$ddf$ds$aux$ddfobj$scale$formula,
      model$ddf$criterion,
      ddf.gof(model$ddf, qq=FALSE)$dsgof$CvM$p,
      summary(model)$ds$average.p,
      summary(model)$ds$average.p.se
    )
  }

  res <- as.data.frame(t(as.data.frame(lapply(models, extract_model_data))),
                        stringsAsFactors=FALSE)

  res[,3] <- as.numeric(res[,3])
  res[,4] <- as.numeric(res[,4])
  res[,5] <- as.numeric(res[,5])
  res[,6] <- as.numeric(res[,6])

  colnames(res) <- c("Key function", "Formula", "AIC", "Cramer-von Mises $p$-value",
                     "$\\hat{P_a}$", "se($\\hat{P_a}$)")

  res[["$\\Delta$AIC"]] <- res$AIC - min(res$AIC, na.rm=TRUE)
  res <- res[order(res$AIC),]

  res
}
```


```{r df-models}
models <- list()

# half-normal models
models$hn <- ds(distdata, truncation=6000, adjustment=NULL)
models$hn.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~SeaState)
models$hn.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~size)
models$hn.ss.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~size+SeaState)
models$hn.survey <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey))
models$hn.survey.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+SeaState)
models$hn.survey.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+size)
models$hn.survey.size.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+size+SeaState)

# hazard-rate models
models$hr <- ds(distdata, truncation=6000, adjustment=NULL, key="hr")
models$hr.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~SeaState, key="hr")
models$hr.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~size, key="hr")
models$hr.ss.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~size+SeaState, key="hr")
models$hr.survey <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey), key="hr")
models$hr.survey.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+SeaState, key="hr")
models$hr.survey.size <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+size, key="hr")
models$hr.survey.size.ss <- ds(distdata, truncation=6000, adjustment=NULL, formula=~as.factor(Survey)+size+SeaState, key="hr")
```

```{r df-results, results="asis"}
kable(make_table(models), digits=3)
```

Plot the best 4 models:

```{r plot-top-models}
par(mfrow=c(2,2))
plot(models$hr.ss)
plot(models$hr)
plot(models$hr.survey.ss)
plot(models$hn.ss)
```

and corresponding qq plots

```{r qqplot-top-models}
par(mfrow=c(2,2))
ddf.gof(models$hr.ss$ddf)
ddf.gof(models$hr$ddf)
ddf.gof(models$hr.survey.ss$ddf)
ddf.gof(models$hn.ss$ddf)
```

Let's go with `hr.ss` for now...

```{r save-models}
df_model <- models$hr.ss
save(df_model, file="df-models.RData")
```



