---
title: Process geographical data
author: David L Miller

---

# Preamble

```{r load-libraries}
library(rgdal)
library(ggplot2)
library(Distance)
library(knitr)
library(dsm)
library(reshape2)
```

# Load and arrange data

```{r effort-data}
effort <- readOGR("Analysis.gdb","Segment_Centroids")
effort <- effort@data
head(effort)
```

```{r rename-effort-cols}
effort$x <- effort$POINT_X
effort$y <- effort$POINT_Y
effort$Effort <- effort$Length
effort$Sample.Label <- effort$SegmentID
```

```{r obs-data}
obs <- readOGR("Analysis.gdb","Sightings")
obs <- obs@data
head(obs)
```

```{r load-df}
load("df-models.RData")
```

```{r rename-obs-cols}
# just save this in 1. at the same time as the model
obs$distance <- obs$Distance
obs$object <- obs$SightingID
obs$Sample.Label <- obs$SegmentID
obs$size <- obs$GroupSize
obs <- obs[obs$distance<=df_hr$ddf$meta.data$width,]
```


# Try a model


```{r dsm-xy}
dsm.xy <- dsm(abundance.est~s(x,y), df_hr, effort, obs, method="REML")
```

```{r dsm-xy-visgam}
# looks like a case for Duchon?
vis.gam(dsm.xy, view=c("x","y"), plot.type="contour", type="response")
```

# Model dissection

```{r dissect-xy}
mod_data <- dsm.xy$data
mod_data$CentreTime <- NULL
mod_data$POINT_X <- NULL
mod_data$POINT_Y <- NULL
mod_data$segment.area <- NULL
mod_data$off.set <- NULL
mod_data$CenterTime <- NULL
mod_data$Effort <- NULL
mod_data$Length <- NULL
mod_data$SegmentID <- NULL

mod_data <- melt(mod_data, id.vars=c("Sample.Label", "abundance.est"))
p <- ggplot(mod_data)
p <- p + geom_histogram(aes(value, weight=abundance.est))
p <- p + facet_wrap(~variable, scale="free")
print(p)
```

Oh hey, look at all those nice interactions!





# Save some data

```{r save-models}
save(effort, obs, file="sperm-data.RData")
```

