---
title: Density surface models
author: David L Miller

---

# Load some data and packages

```{r load-data-packages}
library(Distance)
library(dsm)
library(ggplot2)
load("sperm-data.RData")
load("df-models.RData")
```

# Fit some models


## quasipoisson

only small reduction in %dev (0.1%) when removing EKE

disttoCAS could be removed -- what about biological relevance? Smooth looks like the story we know (but big uncertainty)

```{r fit-models-qp}
k2 <- 30
k1 <- 10

dsm.big.qp <- dsm(count~s(x,y, k=k2)+
                                s(Depth, k=k1)+
                                s(DistToCAS, k=k1),#+
#                                s(SST, k=k1)+
#                                s(EKE, k=k1),#+
#                                s(NPP, k=k1),
               family=quasipoisson(),
               df_hr, effort, obs, method="REML")
summary(dsm.big.qp)
```

checking plots

```{r qp-check}
gam.check(dsm.big.qp)
```


plot that

```{r qp-plot}
plot(dsm.big.qp, pages=1)
```


## Tweedie

```{r fit-models-tw}
dsm.big.tw <- dsm(count~ #s(x,y, k=k2)+
                         s(Depth, k=k1)+
#                         s(DistToCAS, k=k1)+
                         s(SST, k=k1),#+
#                         s(EKE, k=k1),#+
#                         s(NPP, k=k1),
               family=tw(),
               df_hr, effort, obs, method="REML")
summary(dsm.big.tw)
```

```{r tw-check}
gam.check(dsm.big.tw)
```

```{r tw-rq-check}
rqgam.check(dsm.big.tw)
```


## negative binomial

```{r fit-models-qp}
dsm.big.nb <- dsm(count~
#                        s(x,y, k=k2)+
                        s(Depth, k=k1)+
#                        s(DistToCAS, k=k1)+
#                        s(SST, k=k1)+
                        s(EKE, k=k1),#+
#                        s(NPP, k=k1),
               family=nb(),
               df_hr, effort, obs, method="REML")
summary(dsm.big.nb)
```

```{r nb-check}
gam.check(dsm.big.nb)
```

```{r nb-rq-check}
rqgam.check(dsm.big.nb)
```

Do a comparison with `select=TRUE`?


